### ISSUE TITLE
Ports might be undefined

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative-elm#2]
In this case, don't do anything. The reason for this is that Elm does dead code elimination, so if the port is not used yet, it will be undefined. Additionally, it might be the user doesn't need the wnfs stuff, so they could skip that port definition and just do the webnative one.

**Comment by matheus23** [comment]
> In this case, don't do anything

*Do* print a warning. If the user intended to use the port but made a typo it'd otherwise fail silently.

**Comment by icidasset** [comment]
Fixed in v2
