### ISSUE TITLE
Merge webnativeRequest and wnfsRequest into one port

### ISSUE THREAD

**Issue by matheus23** [fission-suite/webnative-elm#3]
At the moment you have to define both these ports:
```elm
port webnativeRequest : Webnative.Request -> Cmd msg
port wnfsRequest : Webnative.Request -> Cmd msg
```

Since they share the same type, you can mix them up. Doing so will lead to a runtime error.

Proposed change: Wrap the `Webnative.Request` type with another custom type / add a field to it to indicate what the intended action is.

**Comment by icidasset** [comment]
Implemented in v2
