### ISSUE TITLE
Wnfs.publish returns empty error message

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative-elm#5]
```
Err (Just Wnfs, "")
```
Not entirely sure this comes from `publish`.

**Comment by matheus23** [comment]
Noticed this, too. I think it's because of this line
https://github.com/fission-suite/webnative-elm/blob/7ae3bfb89f509ce5d9e47b5c0afab855408ee68c/src/Wnfs.elm#L126

**Comment by matheus23** [comment]
So usually you'd provide a `tag` yourself for other WNFS functions like `ls`, `rm`, etc.
But `publish` just sets the tag to an empty string, so if your tag parser doesn't expect that, it'll error.

**Comment by icidasset** [comment]
> So usually you'd provide a `tag` yourself for other WNFS functions like `ls`, `rm`, etc.
> But `publish` just sets the tag to an empty string, so if your tag parser doesn't expect that, it'll error.

Oohhh, good catch, thanks! 👏

**Comment by icidasset** [comment]
Fixed in v3, also added an `Error` type so we can tell where the error message is exactly coming from.
